// <auto-generated />
using System;
using FormationManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormationManager.Migrations
{
    [DbContext(typeof(FormationDbContext))]
    [Migration("20260121230100_QualiopiIndicatorsSiteUnique")]
    partial class QualiopiIndicatorsSiteUnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FormationManager.Models.ActionVeille", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Duree")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormateurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Preuves")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DateAction");

                    b.HasIndex("FormateurId");

                    b.HasIndex("Type");

                    b.ToTable("ActionsVeille");
                });

            modelBuilder.Entity("FormationManager.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroOPCA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SIRET")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeClient")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom");

                    b.HasIndex("SIRET")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("FormationManager.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Donnees")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StagiaireId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatutValidation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeDocument")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ValideurId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SessionId");

                    b.HasIndex("StagiaireId");

                    b.HasIndex("StatutValidation");

                    b.HasIndex("TemplateId");

                    b.HasIndex("TypeDocument");

                    b.HasIndex("ValideurId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("FormationManager.Models.Formation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DureeHeures")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("EstPublique")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModalitesEvaluation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModalitesPedagogiques")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prerequis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixIndicatif")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Programme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferencesQualiopi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Titre");

                    b.ToTable("Formations");
                });

            modelBuilder.Entity("FormationManager.Models.IndicateurQualiopi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeIndicateur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Critere")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NiveauPreuveRequis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Critere");

                    b.HasIndex("SiteId", "CodeIndicateur")
                        .IsUnique();

                    b.ToTable("IndicateursQualiopi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodeIndicateur = "1",
                            CreePar = "system",
                            Critere = 1,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Information du public",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 2,
                            CodeIndicateur = "2",
                            CreePar = "system",
                            Critere = 1,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Indicateurs de résultats",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 3,
                            CodeIndicateur = "3",
                            CreePar = "system",
                            Critere = 1,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Taux d'obtention des certifications",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 4,
                            CodeIndicateur = "4",
                            CreePar = "system",
                            Critere = 2,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Analyse du besoin",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 5,
                            CodeIndicateur = "5",
                            CreePar = "system",
                            Critere = 2,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Objectifs de la prestation",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 6,
                            CodeIndicateur = "6",
                            CreePar = "system",
                            Critere = 2,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Contenus et modalités",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 7,
                            CodeIndicateur = "7",
                            CreePar = "system",
                            Critere = 2,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Contenus et exigences",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 8,
                            CodeIndicateur = "8",
                            CreePar = "system",
                            Critere = 2,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Positionnement à l'entrée",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 9,
                            CodeIndicateur = "9",
                            CreePar = "system",
                            Critere = 3,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Conditions de déroulement",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 10,
                            CodeIndicateur = "10",
                            CreePar = "system",
                            Critere = 3,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Adaptation de la prestation",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 11,
                            CodeIndicateur = "11",
                            CreePar = "system",
                            Critere = 3,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Atteinte des objectifs",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 12,
                            CodeIndicateur = "12",
                            CreePar = "system",
                            Critere = 3,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Engagement des bénéficiaires",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 13,
                            CodeIndicateur = "13",
                            CreePar = "system",
                            Critere = 3,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Coordination des apprentis",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 14,
                            CodeIndicateur = "14",
                            CreePar = "system",
                            Critere = 3,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Exercice de la citoyenneté",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 15,
                            CodeIndicateur = "15",
                            CreePar = "system",
                            Critere = 3,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Droits et devoirs de l'apprenti",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 16,
                            CodeIndicateur = "16",
                            CreePar = "system",
                            Critere = 3,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Présentation à la certification",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 17,
                            CodeIndicateur = "17",
                            CreePar = "system",
                            Critere = 4,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Moyens humains et techniques",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 18,
                            CodeIndicateur = "18",
                            CreePar = "system",
                            Critere = 4,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Coordination des acteurs",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 19,
                            CodeIndicateur = "19",
                            CreePar = "system",
                            Critere = 4,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Ressources pédagogiques",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 20,
                            CodeIndicateur = "20",
                            CreePar = "system",
                            Critere = 4,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Personnels dédiés",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 21,
                            CodeIndicateur = "21",
                            CreePar = "system",
                            Critere = 5,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Compétences des acteurs",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 22,
                            CodeIndicateur = "22",
                            CreePar = "system",
                            Critere = 5,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Gestion de la compétence",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 23,
                            CodeIndicateur = "23",
                            CreePar = "system",
                            Critere = 6,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Veille légale et réglementaire",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 24,
                            CodeIndicateur = "24",
                            CreePar = "system",
                            Critere = 6,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Veille des emplois et métiers",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 25,
                            CodeIndicateur = "25",
                            CreePar = "system",
                            Critere = 6,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Veille pédagogique et technologique",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 26,
                            CodeIndicateur = "26",
                            CreePar = "system",
                            Critere = 6,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Situation de handicap",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 27,
                            CodeIndicateur = "27",
                            CreePar = "system",
                            Critere = 6,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Disposition sous-traitance",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 28,
                            CodeIndicateur = "28",
                            CreePar = "system",
                            Critere = 6,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Formation en situation de travail",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 29,
                            CodeIndicateur = "29",
                            CreePar = "system",
                            Critere = 6,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Insertion professionnelle",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 30,
                            CodeIndicateur = "30",
                            CreePar = "system",
                            Critere = 7,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Recueil des appréciations",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 31,
                            CodeIndicateur = "31",
                            CreePar = "system",
                            Critere = 7,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Traitement des réclamations",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        },
                        new
                        {
                            Id = 32,
                            CodeIndicateur = "32",
                            CreePar = "system",
                            Critere = 7,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Libelle = "Amélioration continue",
                            ModifiePar = "system",
                            NiveauPreuveRequis = 1,
                            SiteId = "SITE_01"
                        });
                });

            modelBuilder.Entity("FormationManager.Models.PreuveQualiopi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommentaireValidation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstValide")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndicateurQualiopiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstValide");

                    b.HasIndex("SessionId");

                    b.HasIndex("IndicateurQualiopiId", "SessionId");

                    b.ToTable("PreuvesQualiopi");
                });

            modelBuilder.Entity("FormationManager.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstPublique")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormateurId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NombreMaxStagiaires")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Programmée");

                    b.HasKey("Id");

                    b.HasIndex("DateDebut");

                    b.HasIndex("FormateurId");

                    b.HasIndex("FormationId");

                    b.HasIndex("Statut");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("FormationManager.Models.SessionClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NombrePlaces")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TarifNegocie")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TypeFinancement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SessionId", "ClientId")
                        .IsUnique();

                    b.ToTable("SessionClients");
                });

            modelBuilder.Entity("FormationManager.Models.Site", b =>
                {
                    b.Property<string>("SiteId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("SiteId");

                    b.HasIndex("Name");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("FormationManager.Models.Stagiaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AttestationGeneree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommentairesEvaluation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateAttestation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstPresent")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EvaluationAChaud")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EvaluationAFroid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HeuresPresence")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StatutInscription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("ClientId", "Nom", "Prenom");

                    b.ToTable("Stagiaires");
                });

            modelBuilder.Entity("FormationManager.Models.TemplateDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Styles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeDocument")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TypeDocument");

                    b.ToTable("TemplatesDocument");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            Contenu = "<html><body><h1>Convention de formation</h1>{{formation.titre}}</body></html>",
                            CreePar = "system",
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiePar = "system",
                            Nom = "Convention de formation",
                            SiteId = "SITE_01",
                            Styles = "",
                            TypeDocument = 0,
                            Variables = "{\"formation.titre\":\"Titre de la formation\"}"
                        },
                        new
                        {
                            Id = 2,
                            Actif = true,
                            Contenu = "<html><body><h1>Attestation</h1>{{stagiaire.nom}} {{stagiaire.prenom}}</body></html>",
                            CreePar = "system",
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiePar = "system",
                            Nom = "Attestation de fin de formation",
                            SiteId = "SITE_01",
                            Styles = "",
                            TypeDocument = 2,
                            Variables = "{\"stagiaire.nom\":\"Nom du stagiaire\",\"stagiaire.prenom\":\"Prénom du stagiaire\"}"
                        },
                        new
                        {
                            Id = 3,
                            Actif = true,
                            Contenu = "<html><body><h1>Feuille d'émargement</h1>{{session.titre}}</body></html>",
                            CreePar = "system",
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModification = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiePar = "system",
                            Nom = "Émargement",
                            SiteId = "SITE_01",
                            Styles = "",
                            TypeDocument = 3,
                            Variables = "{\"session.titre\":\"Titre de la session\"}"
                        });
                });

            modelBuilder.Entity("FormationManager.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biographie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Competences")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Formations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiePar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("Role");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FormationManager.Models.ActionVeille", b =>
                {
                    b.HasOne("FormationManager.Models.Utilisateur", "Formateur")
                        .WithMany()
                        .HasForeignKey("FormateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formateur");
                });

            modelBuilder.Entity("FormationManager.Models.Document", b =>
                {
                    b.HasOne("FormationManager.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FormationManager.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FormationManager.Models.Stagiaire", "Stagiaire")
                        .WithMany()
                        .HasForeignKey("StagiaireId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FormationManager.Models.TemplateDocument", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FormationManager.Models.Utilisateur", "Valideur")
                        .WithMany()
                        .HasForeignKey("ValideurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Session");

                    b.Navigation("Stagiaire");

                    b.Navigation("Template");

                    b.Navigation("Valideur");
                });

            modelBuilder.Entity("FormationManager.Models.PreuveQualiopi", b =>
                {
                    b.HasOne("FormationManager.Models.IndicateurQualiopi", "Indicateur")
                        .WithMany()
                        .HasForeignKey("IndicateurQualiopiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormationManager.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indicateur");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("FormationManager.Models.Session", b =>
                {
                    b.HasOne("FormationManager.Models.Utilisateur", "Formateur")
                        .WithMany()
                        .HasForeignKey("FormateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FormationManager.Models.Formation", "Formation")
                        .WithMany("Sessions")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formateur");

                    b.Navigation("Formation");
                });

            modelBuilder.Entity("FormationManager.Models.SessionClient", b =>
                {
                    b.HasOne("FormationManager.Models.Client", "Client")
                        .WithMany("SessionClients")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormationManager.Models.Session", "Session")
                        .WithMany("SessionClients")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("FormationManager.Models.Stagiaire", b =>
                {
                    b.HasOne("FormationManager.Models.Client", "Client")
                        .WithMany("Stagiaires")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormationManager.Models.Session", "Session")
                        .WithMany("Stagiaires")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("FormationManager.Models.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("FormationManager.Models.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormationManager.Models.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("FormationManager.Models.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormationManager.Models.Client", b =>
                {
                    b.Navigation("SessionClients");

                    b.Navigation("Stagiaires");
                });

            modelBuilder.Entity("FormationManager.Models.Formation", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("FormationManager.Models.Session", b =>
                {
                    b.Navigation("SessionClients");

                    b.Navigation("Stagiaires");
                });
#pragma warning restore 612, 618
        }
    }
}
